apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deploy
  labels:
    env: dev
    app: sonarqube
    project: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://pod/postgres-statefulset-0.postgres-service:5432/sonarqubedb"
        - name: SONARQUBE_JDBC_USERNAME
          value: sonarqube
        - name: SONARQUBE_JDBC_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30002
  type: NodePort
