apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: dockette/nexus
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      volumes:
      - name: nexus-data
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30003
  type: NodePort
