apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deploy
  labels:
    env: dev
    app: nexus
    project: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30003

