apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    env: dev
    app: postgres
    project: javawebapp
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: sonarqubedb
        - name: POSTGRES_USER
          value: sonarqube
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: pg-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pg-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: pg-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-004712b7d74b095c5
    volumeAttributes:
      mounttargetip: "10.0.0.179"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pg-sc
  resources:
    requests:
      storage: 4Gi