apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappp
        image: rahulprakash05/javawebapp:1.0
        ports:
        - containerPort: 8080
